[1,"Error occurred during cleanup: Error: The process cannot access the file because it is being used by another process. (os error 32): remove 'C:\\Users\\locca\\AppData\\Local\\Temp\\quarto-sessiona6e72543871282c1'\n"]
